site_name = "Rygen blog"
site_url = "https://example.com"
site_desc = "Blog about interesting things"

pages = [ "index", "about", "blog" ]

[post.example]
title = "Example post"
tags = [ "example", "markdown" ]
date = 2023-01-01
desc = "Showcasing the features of Markdown"
